# permissions for end users to edit repositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: repository-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gitbackup
    app.kubernetes.io/part-of: gitbackup
    app.kubernetes.io/managed-by: kustomize
  name: repository-editor-role
rules:
- apiGroups:
  - gitbackup.ebiiim.com
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitbackup.ebiiim.com
  resources:
  - repositories/status
  verbs:
  - get
