apiVersion: gitbackup.ebiiim.com/v1beta1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/name: repository
    app.kubernetes.io/instance: repository-sample
    app.kubernetes.io/part-of: gitbackup
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gitbackup
  name: repository-sample
spec:
  # TODO(user): Add fields here
