apiVersion: gitbackup.ebiiim.com/v1beta1
kind: Repository
metadata:
  name: repository-sample
spec:
  src: https://github.com/ebiiim/gitbackup
  dst: https://gitlab.com/ebiiim/gitbackup
  # backup daily at 0600
  schedule: "0 6 * * *"
  # (optional) specify a secret resource in the same namespace
  gitCredentials:
    name: gitcredentials-sample
  # (optional) specify a secret resource in the same namespace
  gitConfig:
    name: gitconfig-sample
