on:
  push:
    tags:
      - "v*"
jobs:
  image:
    name: Push container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository_owner }}/gitbackup-controller
          tags: |
            type=semver,pattern=v{{version}}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: REGISTRY=ghcr.io/${{ github.repository_owner }} ./hack/dist-manifests.sh
      - uses: softprops/action-gh-release@v1
        with:
          files: gitbackup.yaml
